version: "3.1"

services:
  db:
    restart: always
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=topfood
      - POSTGRES_USER=topfood
      - POSTGRES_PASSWORD=topfood
  pgadmin:
      image: dpage/pgadmin4
      depends_on:
        - db
      ports:
        - "5051:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: topfood
      restart: always
  redis:
    image: redis:latest
