# Generated by Django 4.1.7 on 2023-03-30 12:55

from django.db import migrations, models
import food_point.models


class Migration(migrations.Migration):

    dependencies = [
        ("food_point", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to=food_point.models.pdf_path),
        ),
    ]
