# Generated by Django 4.1.7 on 2023-04-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_point", "0003_alter_check_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="order",
            field=models.JSONField(),
        ),
    ]
